version: "3.8"

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud-db-prod
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
    networks:
      - traefik-prod-1

  nextcloud_app:
    image: nextcloud
    container_name: nextcloud-app-prod
    restart: always
    links:
      - nextcloud_db
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.nextcloud-app-prod.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud-http.rule=Host(`nextcloud.homelabwalid.uk`)"
      - "traefik.http.routers.nextcloud-https.rule=Host(`nextcloud.homelabwalid.uk`)"
      - "traefik.http.routers.nextcloud-https.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-http.entrypoints=web"
      - "traefik.http.routers.nextcloud-https.tls=true"
      - "traefik.http.routers.nextcloud-https.tls.certresolver=production"
      - "traefik.http.routers.nextcloud-https.tls.domains[0].main=nextcloud.homelabwalid.uk"
      - "traefik.http.routers.nextcloud-https.tls.domains[0].sans=*.nextcloud.homelabwalid.uk"
      - "traefik.http.routers.nextcloud-https.middlewares=crowdsec@file"
    networks:
      - traefik-prod-1

  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - app_data:/var/www/html
    networks:
      - traefik-prod-1

  onlyoffice-document-server:
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_ENABLED=true
      #- JWT_HEADER=AuthorizationJWT
      - JWT_SECRET=changeme
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.onlyoffice-prod-1.loadbalancer.server.port=80"
      - "traefik.http.routers.onlyoffice-http.rule=Host(`onlyoffice.homelabwalid.uk`)"
      - "traefik.http.routers.onlyoffice-https.rule=Host(`onlyoffice.homelabwalid.uk`)"
      - "traefik.http.routers.onlyoffice-https.entrypoints=websecure"
      - "traefik.http.routers.onlyoffice-http.entrypoints=web"
      - "traefik.http.routers.onlyoffice-https.tls=true"
      - "traefik.http.routers.onlyoffice-https.tls.certresolver=production"
      - "traefik.http.routers.onlyoffice-https.tls.domains[0].main=onlyoffice.homelabwalid.uk"
      - "traefik.http.routers.onlyoffice-https.tls.domains[0].sans=*.onlyoffice.homelabwalid.uk"
      - "traefik.http.routers.onlyoffice-https.middlewares=onlyoffice-headers@file"
    networks:
      - traefik-prod-1

volumes:
  app_data:

networks:
  traefik-prod-1:
    external: true
