version: "3.8"

services:
  postgres:
    image: docker.io/library/postgres:16.3
    container_name: authentik-db-prod-1
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-authentik}
      - POSTGRES_PASSWORD=$${POSTGRES_PASSWORD:-Walid000@}
      - POSTGRES_DB=${POSTGRES_DB:-authentik}
      - TZ=${TZ:-UTC}
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready -U "${POSTGRES_USER:-authentik}"' ]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - traefik-prod-1

  redis:
    image: docker.io/library/redis:7.2.5
    container_name: authentik-redis-prod-1
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - traefik-prod-1

  server:
    image: ghcr.io/goauthentik/server:2025.6.4
    container_name: authentik-server-prod-1
    command: server
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis-prod-1
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db-prod-1
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=$${POSTGRES_PASSWORD:-Walid000@}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_PROMETHEUS__ENABLED="true"
      - AUTHENTIK_PROMETHEUS__LISTEN="0.0.0.0:9300"
    ports:
      - "9300:9300"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.authentik-server-prod-1.loadbalancer.server.port=9000"
      - "traefik.http.routers.authentik-http.rule=Host(`authentik.mydomain.uk`)"
      - "traefik.http.routers.authentik-https.rule=Host(`authentik.mydomain.uk`)"
      - "traefik.http.routers.authentik-https.entrypoints=websecure"
      - "traefik.http.routers.authentik-http.entrypoints=web"
      - "traefik.http.routers.authentik-https.tls=true"
      - "traefik.http.routers.authentik-https.tls.certresolver=production"
      - "traefik.http.routers.authentik-https.tls.domains[0].main=authentik.mydomain.uk"
      - "traefik.http.routers.authentik-https.tls.domains[0].sans=*.authentik.mydomain.uk"
      - "traefik.http.routers.authentik-https.middlewares=crowdsec@file"
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - traefik-prod-1

  worker:
    image: ghcr.io/goauthentik/server:2025.6.4
    container_name: authentik-worker-prod-1
    command: worker
    environment:
      - AUTHENTIK_REDIS__HOST=authentik-redis-prod-1
      - AUTHENTIK_POSTGRESQL__HOST=authentik-db-prod-1
      - AUTHENTIK_POSTGRESQL__USER=${POSTGRES_USER:-authentik}
      - AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}
      - AUTHENTIK_POSTGRESQL__PASSWORD=$${POSTGRES_PASSWORD:-Walid000@}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - traefik-prod-1

volumes:
  postgres_data:
    driver: local

  redis_data:
    driver: local

networks:
  traefik-prod-1:
    external: true
